title: Learning Git and GitHub
author: Abd Samad
email: abdsamad2678@gmail.com
description: Meet Me..
I'm Abd Samad, a Junior Developer passionate about creating awesome apps

# social links
twitter_username: MusiliuSamad # DO NOT include the @ character, or else the build will fail!
github_username:  abdsamad-01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
